formatter: "markdown table"
version: "0.17"
header-from: main.tf
footer-from: ""
recursive:
  enabled: true
  path: "."
sections:
  hide: []
  show: []
content: |-
  ## Usage
  Basic usage of this module is as follows:
  ```
  {{- $module_resource_counter := 0 }}
  {{- $path_slice_counter := 0 }}
  {{- range .Module.Resources }}
    {{- $module_resource_counter = add $module_resource_counter 1 }}
    {{- if ge $module_resource_counter 1 }}
    {{- $module_path := .Position.Filename }}
    {{- $pathname := splitList "/" $module_path }}
    {{- range $pathname }}
      {{- $path_slice_counter = add $path_slice_counter 1 }}
      {{- if eq $path_slice_counter 2 }}
        {{- $path_name := . }}
  module "{{ $path_name }}" {
    source  = "git::https://github.com/ipsos-cicd-tools/<repo name>//modules/{{ $path_name }}?ref=<version number>"
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Module.RequiredInputs }}
    {{"\n"}}  ## Required Variables ##
    {{- range .Module.RequiredInputs }}
    {{ .Name }}  = {{ .GetValue }}
    {{- end }}
    {{- end }}
    {{- if .Module.OptionalInputs }}
    {{"\n"}}  ## Optional Variables ##
    {{- range .Module.OptionalInputs }}
    {{ .Name }}  = {{ printf "  " }}{{ .GetValue | printf "%s" }}
    {{- end }}
    {{- end }}
  {{- if ge $path_slice_counter 1 }}
  }
  {{- end }}
  ```
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
    {{ .Content }}
    <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
